# Generated by Django 3.2.7 on 2021-12-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConnectToHealMain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapistModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('aboutMe', models.CharField(max_length=1024)),
                ('workExperience', models.CharField(max_length=1024)),
                ('pricePerSession', models.IntegerField()),
                ('cover', models.ImageField(default='default.jpg', upload_to='profilephotos')),
            ],
        ),
    ]
