# Generated by Django 3.2.7 on 2021-12-26 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ConnectToHealMain', '0002_therapistmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAppointmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uploader_info', models.CharField(editable=False, max_length=100, null=True)),
                ('therapistName', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('date', models.DateField()),
                ('fromTime', models.TimeField()),
                ('toTime', models.TimeField()),
                ('sessionstatus', models.CharField(default='no', max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
