# Generated by Django 3.2.7 on 2022-01-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConnectToHealMain', '0005_alter_bookappointmentmodel_sessionstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointmentmodel',
            name='sessionLink',
            field=models.CharField(default='#', max_length=250),
        ),
    ]
