# Generated by Django 3.2.7 on 2022-05-27 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConnectToHealMain', '0007_post_replie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscussionModel',
        ),
    ]
